### ISSUE TITLE
etcd dependency problem

### ISSUE THREAD

**Issue by outshow** [micro/go-config#105]
go-config depends `github.com/micro/go-micro v1.1.0` 
and go-micro depends `github.com/coreos/etcd v3.3.12+incompatible // indirect`
and unfortunaly my project depands `go.etcd.io/etcd v3.3.12+incompatible`.

Seems that the same etcd dependency with different path is why the error occurres below:

`2019/05/22 14:29:12 proto: duplicate proto type registered: mvccpb.KeyValue
2019/05/22 14:29:12 proto: duplicate proto type registered: mvccpb.Event
panic: proto: duplicate enum registered: mvccpb.Event_EventType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        ...../vendor/github.com/golang/protobuf/proto/properties.go:459
go.etcd.io/etcd/mvcc/mvccpb.init.0()
        ...../vendor/go.etcd.io/etcd/mvcc/mvccpb/kv.pb.go:107 +0x18a`

'go.etcd.io/etcd' is the offical recommendation import path.
Please refer to https://github.com/etcd-io/etcd/tree/master/clientv3. Thank you very much.

**Comment by outshow** [comment]
I am not sure the is the root cause of the problem.

**Comment by outshow** [comment]
`package main

import (
	"log"

	_ "github.com/coreos/etcd/mvcc/mvccpb"
	_ "go.etcd.io/etcd/mvcc/mvccpb"
)


func main() {
	log.Println("wawa")
}`

I tested with the above code, the same error occurred.

so I think may be the `go-config/source/etcd/etcd.go` is the root case.

**Comment by asim** [comment]
Do you have a solution for this?

**Comment by outshow** [comment]
Not yet. I would try.

**Comment by outshow** [comment]
I have modified `github.com/micro/go-config/source/etcd/etcd.go` and `github.com/micro/go-config/source/etcd/util.go` files in my local vendor folder and this problem is solved. 
The primary point is removing the dependency of `go.etcd.io/etcd/mvcc/mvccpb` from the two files, I am not sure the changes are suitable for the project, so I attach them here(I have add txt subffix for uploading), please take a look in it, Thank you @asim 

[util.go.txt](https://github.com/micro/go-config/files/3211481/util.go.txt)
[etcd.go.txt](https://github.com/micro/go-config/files/3211482/etcd.go.txt)

**Comment by outshow** [comment]
When tring to fix this issue, I find some places can be implement better:
1. current ectd only supports "/" as the key separator, others like '.' dot should be considered, it is good to make it as Option.
2. current ectd only support json string as value likes `etcdctl put app/conf/bbb/ '{"a": 1}'`, ortherise `e.Decode(v, &vals)` in `util.go` will raise an error.

**Comment by asim** [comment]
The dependency issues have been resolved as go-config moves to go-micro/config. If you want to file any further issues or PR changes please do so there.

**Comment by w3liu** [comment]
@asim I find that this problem still exists.

**Comment by w3liu** [comment]
API server listening at: 127.0.0.1:63206
2019/06/04 11:59:06 proto: duplicate proto type registered: mvccpb.KeyValue
2019/06/04 11:59:06 proto: duplicate proto type registered: mvccpb.Event
panic: proto: duplicate enum registered: mvccpb.Event_EventType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(0x11eba9b, 0x16, 0xc0001599b0, 0xc0001599e0)
	E:/project/golang/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/properties.go:459 +0x14a
go.etcd.io/etcd/mvcc/mvccpb.init.0()
	E:/project/golang/pkg/mod/go.etcd.io/etcd@v3.3.13+incompatible/mvcc/mvccpb/kv.pb.go:107 +0xc7

**Comment by asim** [comment]
Go config has been deprecated. Please use go-micro/config

**Comment by wangjinbei** [comment]
This problem still exists with github.com/micro/go-micro v1.4.0

```
package main

import (
	"github.com/micro/go-micro/config/source/etcd"
)

func main() {

	etcd.NewSource(
		etcd.WithAddress("127.0.0.1:2379"),
		etcd.WithPrefix("/prefix"),
		etcd.StripPrefix(true))
}
```
---
Error: 
 ```
2019/06/04 17:57:34 proto: duplicate proto type registered: mvccpb.KeyValue
2019/06/04 17:57:34 proto: duplicate proto type registered: mvccpb.Event
panic: proto: duplicate enum registered: mvccpb.Event_EventType

```

**Comment by vtolstov** [comment]
You have two imports with different paths to etcd.

вт, 4 июн. 2019 г., 12:59 William Wong <notifications@github.com>:

**Comment by asim** [comment]
Please do not comment here, this project is deprecated
